### ISSUE TITLE
Using with docker-compose for simplification

### ISSUE THREAD

**Issue by aandrushchenko** [waleedka/modern-deep-learning-docker#10]
If you like using docker-compose, you can add following file to the root of your project:

**docker-compose.yml**
```
version: "3"
services:
  mdl:
    image: waleedka/modern-deep-learning
    container_name: modern-ml
    volumes:
      - ./:/host
    ports:
      - "8888:8888"
      - "6006:6006"
```

Mind that project root will be mapped into /host folder instead of entire home dir.

To log into container use:
`docker-compose run mdl`
